# Generated by Django 5.2 on 2025-05-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='planes_apuntados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
